// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPfaO9MF9b5EsT674hliA2pIGmUTXOiNo',
    appId: '1:615963552:web:79904f91c2d54a2731e2c5',
    messagingSenderId: '615963552',
    projectId: 'fasttaxi-accec',
    authDomain: 'fasttaxi-accec.firebaseapp.com',
    storageBucket: 'fasttaxi-accec.appspot.com',
    measurementId: 'G-B9KXXS00P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfcFfq855t5evfpNA0kwvtgYq4TGIXfQY',
    appId: '1:615963552:android:c6f1ca555970348e31e2c5',
    messagingSenderId: '615963552',
    projectId: 'fasttaxi-accec',
    storageBucket: 'fasttaxi-accec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsWZ-TokRYNgDJ3cQ2cIqLtzmGmYUNyjg',
    appId: '1:615963552:ios:d2a33816d94b872931e2c5',
    messagingSenderId: '615963552',
    projectId: 'fasttaxi-accec',
    storageBucket: 'fasttaxi-accec.appspot.com',
    iosBundleId: 'com.example.fastTaxi',
  );
}
